project '教学辅助平台-教师端.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '教学辅助平台-教师端' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 教学辅助平台-教师端
  pod 'Masonry'
  pod 'BmobSDK'
  target '教学辅助平台-教师端Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '教学辅助平台-教师端UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
