project '西邮图书馆.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 platform:ios,'8.0'
target '西邮图书馆' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 西邮图书馆
  pod 'AFNetworking'
  pod 'YYModel'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SSKeychain'
  pod 'SDWebImage'
  target '西邮图书馆Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '西邮图书馆UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
